### ISSUE TITLE
Duplicate folder name

### ISSUE THREAD

**Issue by ijwelch** [sleeptil3/codelockr-react#10]
I was allowed to create 2 folders with identical name. There is no way to remove a folder. Empty folders are shown in sidebar.

**Comment by sleeptil3** [comment]
Go to profile then manage folders. Perhaps I should move it out into the main menu. It is hard to find. Thanks!

**Comment by sleeptil3** [comment]
for now, i changed the menu option at the top to "Settings" to make it more clear its more than just profile settings up there. may play more with placement later
