### ISSUE TITLE
Forgot your password?

### ISSUE THREAD

**Issue by achtur** [sleeptil3/codelockr-react#12]
I registered today and for some reason either my password is not working (special character I used is #... might not be taken properly?) or I typed an incorrect one twice when I registered 🤔 

Anyway, it would be nice to have a "Forgot your password?" for situations like this because now I find myself not being able to access my account 😄...😅...😓...😞

**Comment by sleeptil3** [comment]
An excellent point. I will get on that. it was definitely on the list but got pushed to the back of the mind with other projects that took over! I was actually just working on some issues on CodeLockr yesterday so I will add this to the list to add. When I launched, this was a final project for a bootcamp I was in and I honestly didn't know how to implement a PW reset by email yet! I'll shoot you an email with a password to login for now!

**Comment by achtur** [comment]
I understand 😄 
This sounds great! Thanks for the super quick response!

**Comment by sleeptil3** [comment]
sent PW reset to your email!

**Comment by achtur** [comment]
Thanks! So effective :)
